In [32]:
import numpy as np

a = np.random.randn(2, 3, 4)

b = np.sum(a, axis=0)

c = np.einsum('i...->...', a)

print(b)
print("---------------------")
print(c)
print(c)
print(b==c)

[[-1.83642108 -1.32303485  0.89231883  1.74174622]
 [-0.65090629  2.87800934 -1.27534478 -1.47584017]
 [ 0.42666305 -0.18934454 -0.96991195 -2.81650455]]
---------------------
[[-1.83642108 -1.32303485  0.89231883  1.74174622]
 [-0.65090629  2.87800934 -1.27534478 -1.47584017]
 [ 0.42666305 -0.18934454 -0.96991195 -2.81650455]]
[[-1.83642108 -1.32303485  0.89231883  1.74174622]
 [-0.65090629  2.87800934 -1.27534478 -1.47584017]
 [ 0.42666305 -0.18934454 -0.96991195 -2.81650455]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [6]:
import numpy as np
p = 3
a = np.random.randn(1, 2, 2, 1)

b = np.pad(a, ((0, 0), (p, p), (p, p), (0, 0)), 'constant')
print(b)

KeyboardInterrupt: 