In [9]:
import numpy as np

a = np.random.randn(3, 5)
b = np.random.randn(2, 2, 3)

print(a)

c = np.mean(a, axis=0)
print(c)

[[-0.20872373 -1.63033652  0.63855746  0.12613963 -1.22793191]
 [-1.25844662  1.75393831  0.54504574  0.020129    1.93104849]
 [ 0.24750073 -0.82511197 -0.52365913 -1.04496228  0.04111204]]
[-0.40655654 -0.23383673  0.21998136 -0.29956455  0.24807621]
